SELECT t.MON$TABLE_NAME, r.MON$RECORD_SEQ_READS, r.MON$RECORD_IDX_READS,
  r.MON$RECORD_LOCKS, r.MON$RECORD_WAITS
FROM MON$RECORD_STATS r
JOIN MON$TABLE_STATS t ON r.MON$STAT_ID = t.MON$RECORD_STAT_ID
JOIN RDB$RELATIONS o on o.RDB$RELATION_NAME=t.MON$TABLE_NAME
WHERE o.RDB$SYSTEM_FLAG=0
